### WARNING ###
# This is a yaml file.  Empty lines and comments are fine, but it is important
# to preserve the indentation structure of the keys.  Syntax errors will
# prevent the umirr service from starting.

# Settings specific to MainResource.
main:
  route: /

# Settings specific to MirrorsResource.
mirrors:
  route: /mirrors
  hide_owners: True

# Settings specific to MirrorListResource.
mirrorlist:
  route: /mirrorlist
  show_title: True
  show_source: True
  show_distances: True
  fallback:
    city: San Antonio
    region: TX
    country: US
    coordinates:
      latitude: 29.42575
      longitude: -98.48630
  protocols:
    - http
    - https
    - rsync
    - ftp
  architectures:
    - x86_64
    - i386
    - source
  repos:
    foorepo-centos7: /stable/CentOS/5/@arch@/
    foorepo-centos7-debuginfo: /stable/CentOS/5/@arch@/debuginfo/
    foorepo-centos7-source: /stable/CentOS/5/SRPMS/
    foorepo-centos7-testing: /testing/CentOS/5/@arch@/
    foorepo-centos7-testing-debuginfo: /testing/CentOS/5/@arch@/debuginfo/
    foorepo-centos7-testing-source: /testing/CentOS/5/SRPMS/
    foorepo-centos7-archive: /archive/CentOS/5/@arch@/
    foorepo-centos7-archive-debuginfo: /archive/CentOS/5/@arch@/debuginfo/
    foorepo-centos7-archive-source: /archive/CentOS/5/SRPMS/
