protocols:
  - http
  - https
  - rsync
  - ftp
arches:
  - x86_64
  - i386
  - source
mirrorlist:
  show_title: True
  show_source: True
  show_distances: True
  fallback:
    city: San Antonio
    region: TX
    country: US
    coordinates:
      latitude: 29.42575
      longitude: -98.48630
mirrors:
  hide_owners: True
repos:
  foorepo-centos7: /stable/CentOS/5/@arch@/
  foorepo-centos7-debuginfo: /stable/CentOS/5/@arch@/debuginfo/
  foorepo-centos7-source: /stable/CentOS/5/SRPMS/
  foorepo-centos7-testing: /testing/CentOS/5/@arch@/
  foorepo-centos7-testing-debuginfo: /testing/CentOS/5/@arch@/debuginfo/
  foorepo-centos7-testing-source: /testing/CentOS/5/SRPMS/
  foorepo-centos7-archive: /archive/CentOS/5/@arch@/
  foorepo-centos7-archive-debuginfo: /archive/CentOS/5/@arch@/debuginfo/
  foorepo-centos7-archive-source: /archive/CentOS/5/SRPMS/
